AWSTemplateFormatVersion: '2010-09-09'
Description: 'Sample Template to create IAM Roles and polices'
Resources:
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: aws-iam-sample-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
              - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Tags:
          - Key: "Environment" 
            Value: Test
 DynamoPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: aws-iam-sample-iam-policy 
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'dynamodb:PutItem'
              - 'dynamodb:UpdateItem'
              - 'dynamodb:Query'
              - 'dynamodb:DeleteItem'
              - 'dynamodb:GetItem'
            Resource: '*'
      Roles:
      -  !Ref IAMRole          
